import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {responsiveFontSize as responsiveFont} from 'react-native-responsive-dimensions';
import {Dimensions} from 'react-native';

const styles = StyleSheet.create({
  textContainer: {
    alignItems: 'center',
  },
  corporationContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgLogo: {
    marginTop: 10,
    alignSelf: 'center',
    width: '45%',
    // height: '53%',
    resizeMode: 'contain',
  },
  textQuestion: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(2),
    marginBottom: 10,
    marginTop: 80,
    color: '#4d4d4d',
  },
  corporationNameDescription: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(2),
    marginBottom: 5,
    marginTop: 12,
    color: '#4d4d4d',
  },
  inputUserStyle: {
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: 'rgb(196, 196, 196)',
    borderWidth: 1.8,
    paddingLeft: 14,
    width: wp(60),
    // height: hp(7),
    fontFamily: 'Montserrat-Medium',
  },
  inputGuidance: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.8),
    // color: this.state.clickVerify,
    color: 'red',
    marginTop: 20,
    marginBottom: 9,
  },
  corporationInput: {
    textAlign: 'left',
    paddingLeft: '5%',
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(3),
    height: hp('9'),
    width: wp('70'),
    backgroundColor: 'transparent',
    paddingTop: 0,
  },
  corporationWithCNPJStyle: {
    marginTop: -40,
    marginBottom: 6,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#007f0b',
    borderRadius: 300,
    width: wp(65),
    // height: hp(7),
  },
  corporationWithoutCNPJStyle: {
    marginTop: 8,
    marginBottom: 40,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#808080',
    borderRadius: 300,
    width: wp(65),
    // height: hp(7),
  },
  // NOVO CSS
  container: {
    flex: 1,
    height: Dimensions.get('window').height,
    flexDirection: 'column',
    // alignItems: 'center',
    // borderColor: 'red',
    // borderWidth: 3
  },
  boxLogo: {
    // flex: 0.1,
    height:
      Dimensions.get('window').height -
      (Dimensions.get('window').height / 100) * 90,
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    // borderColor: 'black',
    // borderWidth: 1,
  },
  boxInptEmpresa: {
    // flex: 0.3,
    height:
      Dimensions.get('window').height -
      (Dimensions.get('window').height / 100) * 70,
    justifyContent: 'center',
    alignItems: 'center',
    // borderColor: 'orange',
    // borderWidth: 3,
  },
  boxInptCnpj: {
    flex: 0.4,
    flexDirection: 'column',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    // borderColor: 'blue',
    // borderWidth: 1,
  },
  labelCNPJ: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.8),
    color: '#4d4d4d',
  },
  boxButtons: {
    flex: 0.3,
    height:
      Dimensions.get('window').height -
      (Dimensions.get('window').height / 100) * 70,
    flexDirection: 'column',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    // borderColor: 'green',
    // borderWidth: 1,
  },
  textTitle: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(2.3),
    color: '#4d4d4d',
    marginBottom: 10,
  },
  textTitleInput: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.8),
    color: '#4d4d4d',
    width: '100%',
    marginLeft: 20,
  },
  inputTextEmpresa: {
    padding: 0,
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: 'rgb(196, 196, 196)',
    borderWidth: 1,
    paddingHorizontal: 20,
    width: wp(70),
    height: 40,
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.8),
  },
  btnEmpresaFormal: {
    color: '#808080',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#007f0b',
    borderRadius: 300,
    width: wp(65),
    height: hp(7),
  },
  btnEmpresaInformal: {
    marginTop: 8,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#808080',
    borderRadius: 300,
    width: wp(65),
    height: hp(7),
  },
  textBtn: {
    fontFamily: 'Montserrat-Bold',
    color: '#F3F3F3',
    fontSize: responsiveFont(2),
  },
  textBtnInformal: {
    fontFamily: 'Montserrat-Bold',
    color: '#4d4d4d',
    fontSize: responsiveFont(2),
  },
  inputWarning: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.4),
    alignSelf: 'flex-start',
    color: 'red',
    marginLeft: 20,
    marginTop: 2,
  },
  clearButtonStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp('13.5%'),
    marginLeft: wp('24%'),
    left: wp('54'),
    top: hp('2.6'),
    width: wp('6'),
    height: hp('4'),
    position: 'absolute',
  },
});

export default styles;
