import { StyleSheet, Dimensions } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { responsiveFontSize as responsiveFont } from 'react-native-responsive-dimensions';
import { COLORS } from '../../constantes/colors';

const styles = StyleSheet.create({
  container: {
    flex: hp('100%'),
    flexDirection: 'column',
    backgroundColor: COLORS.BACKGROUND,
    marginTop: hp('3%'),
  },
  containerBtBack: {
    position: 'absolute',
    left: wp('6%'),
    top: hp('3%'),
  },
  btVoltar: {
    position: 'absolute',
    top: wp('4%'),
    left: wp('5%'),
  },
  boxLogo: {
    height: hp('10%'),
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    // borderColor: '#000',
    // borderWidth: 1,
  },
  boxInputs: {
    height: hp('70%'),
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    // borderColor: '#000',
    // borderWidth: 1,
  },
  boxBtn: {
    marginVertical: hp('3%'),
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    // borderColor: '#000',
    // borderWidth: 1,
  },
  img: {
    alignSelf: 'center',
    width: '45%',
    resizeMode: 'contain',
  },
  InputText: {
    padding: 0,
    textAlign: 'left',
    marginBottom: 15,
    paddingHorizontal: '8%',
    height: hp('6%'),
    width: wp('65%'),
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: '#b3b3b3',
    borderWidth: 1,
    fontFamily: 'Montserrat-Medium',
  },
  inputUserStyle: {
    alignSelf: 'center',
    width: wp('65%'),
    // height: hp('7%'),
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: '#b3b3b3',
    borderWidth: 1.8,
    paddingLeft: 25,
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(2),
  },
  inputCPFphoneUserStyle: {
    top: '20%',
    left: '13%',
    borderRadius: 300,
    alignSelf: 'stretch',
    width: wp('75%'),
    // height: hp('7.5%'),
    backgroundColor: 'transparent',
    borderColor: '#b3b3b3',
    borderWidth: 1.8,
    paddingLeft: '10%',
    fontFamily: 'Montserrat-Medium',
  },
  inputCellphoneUserStyle: {
    top: '10%',
    left: '13%',
    borderRadius: 300,
    alignSelf: 'stretch',
    width: wp('75%'),
    // height: hp('7.5%'),
    backgroundColor: 'transparent',
    borderColor: '#b3b3b3',
    borderWidth: 1.8,
    paddingLeft: '10%',
    fontFamily: 'Montserrat-Medium',
  },

  formsStyle: {
    marginBottom: 15,
    width: wp(65),
    // height: hp(7),
    borderRadius: 300,
    paddingLeft: 20,
    textAlign: 'left',
    backgroundColor: 'transparent',
    borderColor: '#b3b3b3',
    borderWidth: 1.8,
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(2),
  },
  textLabel: {
    fontSize: responsiveFont(1.8),
    fontFamily: 'Montserrat-Medium',
    marginBottom:
      Dimensions.get('window').height -
      (Dimensions.get('window').height / 100) * 99.3,
    width: '65%',
  },
  textDescription: {
    // flex: 1,
    // justifyContent: '//flex-start',
    textAlign: 'left',
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
    bottom: 30,
    paddingTop: 30,
  },
  titleStyle: {
    textAlign: 'center',
    fontFamily: 'Montserrat-Medium',
    fontSize: 18,
    marginBottom:
      Dimensions.get('window').height -
      (Dimensions.get('window').height / 100) * 97,
  },
  titleStyle2: {
    textAlign: 'center',
    fontWeight: '900',
    fontFamily: 'Montserrat-Medium',
    fontSize: 18,
    marginBottom:
      Dimensions.get('window').height -
      (Dimensions.get('window').height / 100) * 97,
  },
  secureEntryStyle1: {
    marginBottom: 15,
    width: wp(65),
    borderRadius: 300,
    paddingLeft: 20,
    letterSpacing: 20,
    textAlign: 'center',
    backgroundColor: 'transparent',
    borderColor: '#b3b3b3',
    color: '#808080',
    borderWidth: 1,
    fontFamily: 'Montserrat-Bold',
    fontSize: responsiveFont('2.9'),
  },
  secureEntryStyle2: {
    marginBottom: 15,
    width: wp(65),
    borderRadius: 300,
    paddingLeft: 20,
    letterSpacing: 20,
    textAlign: 'center',
    backgroundColor: 'transparent',
    borderColor: '#b3b3b3',
    borderWidth: 1,
    fontFamily: 'Montserrat-Bold',
    color: '#808080',
    fontSize: responsiveFont('2.9'),
  },
  loginButtonStyle: {
    backgroundColor: '#007f0b',
    elevation: 1,
    marginTop: 50,
    // justifyContent: 'center',
    // alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 300,
    width: wp(65),
    // height: hp(7),
  },
  loginButtonTextStyle: {
    color: 'white',
    fontSize: responsiveFont(2),
    fontFamily: 'Montserrat-Bold',
  },
  eraseButtonName: {
    color: '#808080',
    marginLeft: 245,
    marginTop: -48,
  },
  descriptionContinuation: {
    marginTop: 20,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
  },
  secureBox: {
    padding: 0,
    textAlign: 'center',
    marginBottom: 15,
    height: hp('6%'),
    width: wp('65%'),
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: '#b3b3b3',
    borderWidth: 1,
    fontFamily: 'Montserrat-Medium',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secureText: {
    fontSize: responsiveFont('4.8'),
    fontFamily: 'Montserrat-Medium',
  },
  placeholderPinStyle: {
    textAlign: 'center',
    width: responsiveFont(1),
    height: responsiveFont(1),
    opacity: 0.3,
    backgroundColor: '#808080',
    borderRadius: 25,
  },
  pinMaskStyle: {
    width: responsiveFont(1),
    height: responsiveFont(1),
    borderRadius: 25,
    backgroundColor: '#007f0b',
  },
  clearButtonStyle: {
    width: wp('7'),
    height: hp('5'),
    paddingLeft: wp('2%'),
    left: wp('54'),
    top: hp('5.1%'),
    position: 'absolute',
  },
  inputError: {
    borderColor: '#FF0000',
  },
  modal: {
    // flex: 0.7,
    borderRadius: 10,
  },
  modalHeader: {
    // flex: 0.1,
    // flexDirection: 'row',
    // justifyContent: 'center',
    fontWeight: 'bold',
    borderBottomWidth: 1.5,
    borderColor: 'grey',
    paddingTop: 10,
    backgroundColor: 'white',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  modalContent: {
    // flex: 0.8,
    fontWeight: 'bold',
    backgroundColor: 'white',
    borderBottomWidth: 1.5,
    borderColor: 'grey',
  },
  modalFooter: {
    // flex: 0.15,
    fontWeight: 'bold',
    color: '#000',
    width: '100%',
    backgroundColor: 'white',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  headerText: {
    fontSize: 25,
    fontWeight: '500',
    color: 'red',
    textAlign: 'center',
  },
  imgHeader: {
    width: 40,
    // height: 40,
  },
  MsgContent: {
    fontSize: 20,
    fontWeight: '300',
    color: 'black',
    textAlign: 'center',
    padding: 15,
    marginLeft: 50,
    marginRight: 50,
  },
  MsgErro: {
    marginTop: 35,
    marginLeft: 15,
    fontSize: 20,
    color: 'red',
    textAlign: 'left',
  },
  BtnFecharText: {
    color: 'white',
    fontSize: responsiveFont(2),
    fontFamily: 'Montserrat-Bold',
  },
  BtnFechar: {
    backgroundColor: '#333333',
    marginTop: 10,
    // justifyContent: 'center',
    // alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 300,
    width: 200,
    // height: 45,
  },
});

export default styles;
