import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {responsiveFontSize as responsiveFont} from 'react-native-responsive-dimensions';
import {Dimensions} from 'react-native';
import {COLORS} from '../../../constantes/colors';

const styles = StyleSheet.create({
  container: {
    height: hp(100),
    flexDirection: 'column',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: 'black'
    backgroundColor: COLORS.BACKGROUND,
  },
  containerModalEstado: {
    paddingTop: 10,
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'white',
    borderRadius: 20,

    paddingVertical: 20,
  },
  listagemModalEstado: {
    height: hp(40),
    width: wp(80),
  },
  textTitleModaldEstado: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(2.5),
    color: '#4D4D4D',
    marginBottom: 10,
    marginLeft: 20,
  },
  containerFooterModalEstado: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: wp(80),
    paddingTop: 10,
    paddingHorizontal: 20,
  },
  textButtonFooterModalEstado: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.75),
    color: '#477E22',
  },
  boxLogo: {
    flexDirection: 'column',
    justifyContent: 'center',
    width: wp('80%'),
    height: hp('10%'),
    alignItems: 'center',
    // borderColor: '#000',
    // borderWidth: 1,
  },
  boxRow: {
    flexDirection: 'column',
    justifyContent: 'center',
    width: wp('90%'),
  },
  boxBtn: {
    zIndex: 0,
    flexDirection: 'column',
    justifyContent: 'center',
    //  borderColor: 'black',
    //  borderWidth: 1,
  },
  boxInputs: {
    height: hp(10),
    marginTop: hp('2%'),
    flexDirection: 'row',
    justifyContent: 'space-around',
    // borderColor: 'black',
    // borderWidth: 1,
    // height: Dimensions.get('window').height - ((Dimensions.get('window').height / 100) * 80),
    width: '100%',
  },
  boxTitle: {
    flexDirection: 'column',
    marginTop: hp('3%'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  InputText: {
    paddingVertical: 0,
    paddingHorizontal: 20,
    textAlign: 'left',
    marginBottom: hp('6%'),
    height: hp('6%'),
    fontSize: responsiveFont(1.7),
    borderRadius: 300,
    backgroundColor: '#FFFFFF',
    color: '#333333',
    borderColor: '#B3B3B3',
    borderWidth: 1,
    fontFamily: 'Montserrat-Medium',
  },
  formContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp('50%'),
  },
  containerDescriptions1: {
    flexDirection: 'row',
    marginTop: 20,
    marginBottom: -20,
    marginLeft: 20,
  },
  containerDescriptions2: {
    flexDirection: 'row',
    marginTop: 20,
    marginBottom: -20,
    marginLeft: 20,
  },
  containerDescriptions3: {
    flexDirection: 'row',
    marginTop: -10,
    marginBottom: -20,
  },
  containerForm1: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  containerForm2: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  containerForm3: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  imgLogo: {
    alignSelf: 'center',
    width: '60%',
    height: '60%',
    resizeMode: 'contain',
  },
  descriptionText: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(2),
  },
  description1: {
    fontFamily: 'Montserrat-Medium',
    marginLeft: 7,
    marginBottom: 5,
    fontSize: responsiveFont(2),
    color: '#4d4d4d',
  },
  description2: {
    fontFamily: 'Montserrat-Medium',
    paddingLeft: 9,
    marginBottom: 5,
    fontSize: responsiveFont(2),
    color: '#4d4d4d',
  },
  formatInputZip: {
    padding: 0,
    textAlign: 'center',
    marginBottom: 15,
    height: hp('6%'),
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: '#808080',
    borderWidth: 1,
    fontFamily: 'Montserrat-Medium',
  },
  formatInputStreet: {
    marginLeft: 10,
    textAlign: 'left',
    paddingLeft: 20,
    marginBottom: 15,
    height: hp('7%'),
    width: wp(45),
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: '#808080',
    borderWidth: 1,
    fontFamily: 'Montserrat-Medium',
  },
  formatInputNumber: {
    marginLeft: 10,
    textAlign: 'left',
    paddingLeft: 20,
    marginBottom: 15,
    height: hp('7%'),
    width: wp(18),
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: '#808080',
    borderWidth: 1,
    fontFamily: 'Montserrat-Medium',
  },
  formatInputComplement: {
    marginLeft: 10,
    textAlign: 'left',
    paddingLeft: 20,
    marginBottom: 15,
    height: hp('7%'),
    width: wp(50),
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: '#808080',
    borderWidth: 1,
    fontFamily: 'Montserrat-Medium',
  },
  formatInputDistrict: {
    marginLeft: 10,
    textAlign: 'left',
    paddingLeft: 20,
    marginBottom: 15,
    height: hp('7%'),
    width: wp(73),
    borderRadius: 300,
    backgroundColor: 'transparent',
    borderColor: '#808080',
    borderWidth: 1,
    fontFamily: 'Montserrat-Medium',
  },
  continueButtonStyle: {
    marginTop: 600,
    marginBottom: 70,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#007f0b',
    elevation: 1,
    borderRadius: 300,
    width: wp(65),
    height: hp(7),
    position: 'absolute',
  },
  requiredFields: {
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.5),
    color: '#4d4d4d',
  },
  saveButtonStyle: {
    backgroundColor: '#007f0b',
    elevation: 1,
    marginTop: hp('10%'),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 300,
    width: wp(65),
    height: hp(7),
  },
  buttonChooseOption: {
    color: '#333333',
    padding: 12,
    paddingLeft: 20,
    borderWidth: 1,
    borderRadius: 300,
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.8),
  },
  textModalSelect: {
    color: '#333333',
    fontFamily: 'Montserrat-Medium',
    fontSize: responsiveFont(1.8),
  },
});
//NOVO CSS

export default styles;
